import { FormEvent, RefObject, useEffect, useState } from "react";
import { ChevronDown, ChevronUp } from "lucide-react";
import { Cadence, Memory, MemoryType } from "../api";

const types: MemoryType[] = ["axiom","preference","project","person","decision","concept","source","task","event","artifact","skill","system","note"];
export type ComposerValue = { content: string; type: MemoryType; cadence: Cadence; base_importance: number; sourceUri: string };
export function Composer({ editing, open, resetToken, textareaRef, onOpenChange, onSave, onCancel }: { editing?: Memory; open: boolean; resetToken: number; textareaRef: RefObject<HTMLTextAreaElement | null>; onOpenChange: (open: boolean) => void; onSave: (value: ComposerValue) => Promise<void>; onCancel: () => void }) {
  const [busy,setBusy]=useState(false); const [content,setContent]=useState(""); const [type,setType]=useState<MemoryType>("note"); const [cadence,setCadence]=useState<Cadence>("none"); const [importance,setImportance]=useState(.6); const [sourceUri,setSourceUri]=useState("");
  function resetDraft() { setContent(""); setType("note"); setCadence("none"); setImportance(.6); setSourceUri(""); }
  useEffect(() => { if (editing) { setContent(editing.content); setType(editing.type); setCadence(editing.cadence); setImportance(editing.base_importance); setSourceUri(editing.source_links[0]?.uri ?? ""); } else { resetDraft(); } }, [editing, resetToken]);
  async function submit(event: FormEvent) { event.preventDefault(); if(!content.trim()) return; setBusy(true); try { await onSave({content:content.trim(),type,cadence,base_importance:importance,sourceUri:sourceUri.trim()}); resetDraft(); } finally {setBusy(false);} }
  function cancel() { resetDraft(); onCancel(); }
  return <form className={`composer ${open ? "open" : ""}`} onSubmit={submit}><button type="button" className="composer-toggle" aria-expanded={open} onClick={() => onOpenChange(!open)}>{open?<ChevronUp size={17}/>:<ChevronDown size={17}/>}<strong>{editing ? "Edit memory" : "Add memory"}</strong></button>{open ? <div className="composer-body"><textarea ref={textareaRef} value={content} onChange={event=>setContent(event.target.value)} placeholder="What happened or what should the agent remember?" aria-label="Memory content"/><div className="fields"><label>Type<select value={type} disabled={Boolean(editing)} onChange={event=>setType(event.target.value as MemoryType)}>{types.map(item=><option key={item}>{item}</option>)}</select></label><label>Cadence<select value={cadence} onChange={event=>setCadence(event.target.value as Cadence)}><option>none</option><option>daily</option><option>weekly</option><option>monthly</option><option>seasonal</option></select></label><label>Importance<input type="range" min="0" max="1" step=".05" value={importance} onChange={event=>setImportance(Number(event.target.value))}/></label><label className="source-field">Source URI<input value={sourceUri} onChange={event=>setSourceUri(event.target.value)} placeholder="file:///path/to/source.md#L10"/></label><div className="save-actions">{editing?<button type="button" className="secondary" onClick={cancel}>Cancel</button>:null}<button className="primary" disabled={busy}>{busy ? "Saving…" : editing ? "Save new version" : "Save memory"}</button></div></div></div> : null}</form>;
}
