import { FormEvent, useCallback, useEffect, useMemo, useRef, useState } from "react";
import { Check, Database, Filter, MemoryStick, Menu, Plus, Search, Settings, Sparkles } from "lucide-react";
import { Composer, ComposerValue } from "./components/Composer";
import { GraphView } from "./components/GraphView";
import { Inspector } from "./components/Inspector";
import { Maintenance } from "./components/Maintenance";
import { MemoryTable } from "./components/MemoryTable";
import { GraphResponse, MaintenanceProposal, Memory, MemoryView, SearchScope, VersionHistory, createMemory, decideMaintenance, forgetMemory, getGraph, getVersions, health, listMaintenance, listMemories, previewMaintenance, restoreMemory, searchMemories, updateMemory } from "./api";

type View = "memories" | "maintenance" | "settings";
const filters: MemoryView[] = ["all", "axioms", "forgotten", "expired"];

export function App() {
  const [view,setView]=useState<View>("memories"); const [filter,setFilter]=useState<MemoryView>("all"); const [scope,setScope]=useState<SearchScope>("general"); const [query,setQuery]=useState("");
  const [memories,setMemories]=useState<Memory[]>([]); const [selectedId,setSelectedId]=useState<string>(); const [graph,setGraph]=useState<GraphResponse|null>(null); const [history,setHistory]=useState<VersionHistory|null>(null); const [editing,setEditing]=useState<Memory>(); const [proposals,setProposals]=useState<MaintenanceProposal[]>([]);
  const [online,setOnline]=useState(false); const [databasePath,setDatabasePath]=useState<string>(); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false); const [error,setError]=useState<string>();
  const [composerOpen,setComposerOpen]=useState(true); const [composerResetToken,setComposerResetToken]=useState(0); const [filterOpen,setFilterOpen]=useState(false); const [previewedAt,setPreviewedAt]=useState<string>();
  const searchRef=useRef<HTMLInputElement>(null); const composerRef=useRef<HTMLTextAreaElement>(null); const filterMenuRef=useRef<HTMLDivElement>(null); const requestVersionRef=useRef(0);
  const selected=memories.find(memory=>memory.id===selectedId) ?? graph?.nodes.find(memory=>memory.id===selectedId) ?? graph?.origin;

  const load = useCallback(async (nextFilter: MemoryView) => { const requestVersion=++requestVersionRef.current;setLoading(true);setError(undefined);try{const [items,status]=await Promise.all([listMemories(nextFilter),health()]);if(requestVersion!==requestVersionRef.current)return;setMemories(items);setDatabasePath(status.database_path);setSelectedId(current=>items.some(item=>item.id===current)?current:items[0]?.id);setOnline(true);}catch(reason){if(requestVersion!==requestVersionRef.current)return;setOnline(false);setError(reason instanceof Error?reason.message:"Could not reach local API");}finally{if(requestVersion===requestVersionRef.current)setLoading(false);}},[]);
  useEffect(()=>{void load(filter);},[filter,load]);
  useEffect(()=>{void listMaintenance().then(setProposals).catch(()=>undefined);},[]);
  useEffect(()=>{if(!selectedId){setGraph(null);setHistory(null);return;} let active=true; Promise.all([getGraph(selectedId),getVersions(selectedId)]).then(([nextGraph,nextHistory])=>{if(active){setGraph(nextGraph);setHistory(nextHistory);}}).catch(()=>{if(active){setGraph(null);setHistory(null);}}); return()=>{active=false};},[selectedId]);
  useEffect(()=>{const handleKey=(event:KeyboardEvent)=>{if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==="k"){event.preventDefault();setView("memories");requestAnimationFrame(()=>{searchRef.current?.focus();searchRef.current?.select();});}if(event.key==="Escape")setFilterOpen(false);};document.addEventListener("keydown",handleKey);return()=>document.removeEventListener("keydown",handleKey);},[]);
  useEffect(()=>{if(!filterOpen)return;const close=(event:MouseEvent)=>{if(!filterMenuRef.current?.contains(event.target as Node))setFilterOpen(false);};document.addEventListener("mousedown",close);return()=>document.removeEventListener("mousedown",close);},[filterOpen]);

  const visibleMemories=useMemo(()=>{ if(filter==="forgotten") return memories.filter(memory=>memory.is_forgotten); if(filter==="expired") return memories.filter(memory=>memory.expires_at && new Date(memory.expires_at)<=new Date()); return [...memories].sort((a,b)=>(b.rank??0)-(a.rank??0)); },[memories,filter]);
  async function submitSearch(event:FormEvent){event.preventDefault();const trimmedQuery=query.trim();if(!trimmedQuery){await load(filter);return;}const requestVersion=++requestVersionRef.current;setLoading(true);setError(undefined);try{const result=await searchMemories(trimmedQuery,scope,filter);if(requestVersion!==requestVersionRef.current)return;setMemories(result.results);setSelectedId(result.results[0]?.id);}catch(reason){if(requestVersion===requestVersionRef.current)setError(reason instanceof Error?reason.message:"Search failed");}finally{if(requestVersion===requestVersionRef.current)setLoading(false);}}
  async function save(value:ComposerValue){try{const links=value.sourceUri?[{label:value.sourceUri,kind:"manual",uri:value.sourceUri}]:[];const memory=editing?await updateMemory(editing.id,{content:value.content,cadence:value.cadence,base_importance:value.base_importance,source_links:links}):await createMemory({type:value.type,content:value.content,cadence:value.cadence,base_importance:value.base_importance,source:"manual-ui",source_links:links});setEditing(undefined);setFilter("all");await load("all");setSelectedId(memory.id);}catch(reason){setError(reason instanceof Error?reason.message:"Save failed");throw reason;}}
  async function forget(){if(!selected)return;const reason=window.prompt("Why should this memory be forgotten?", "outdated or no longer relevant");if(reason===null)return;try{await forgetMemory(selected.id,reason);await load(filter);}catch(cause){setError(cause instanceof Error?cause.message:"Forget failed");}}
  async function restore(){if(!selected)return;try{await restoreMemory(selected.id);await load(filter);setSelectedId(selected.id);}catch(cause){setError(cause instanceof Error?cause.message:"Restore failed");}}
  async function runPreview(){setBusy(true);setError(undefined);try{const run=await previewMaintenance();setProposals(run.proposals);setPreviewedAt(run.created_at);}catch(reason){setError(reason instanceof Error?reason.message:"Maintenance preview failed");}finally{setBusy(false);}}
  async function decide(id:string,action:"apply"|"dismiss"){setBusy(true);setError(undefined);try{const result=await decideMaintenance(id,action);setProposals(current=>current.map(item=>item.id===id?result.proposal:item));if(action==="apply")await load(filter);}catch(reason){setError(reason instanceof Error?reason.message:"Maintenance action failed");}finally{setBusy(false);}}
  function startNewMemory(){setView("memories");setEditing(undefined);setComposerResetToken(value=>value+1);setComposerOpen(true);requestAnimationFrame(()=>composerRef.current?.focus());}
  function startEditing(){if(!selected?.is_current)return;setEditing(selected);setComposerOpen(true);requestAnimationFrame(()=>composerRef.current?.focus());}
  function selectFilter(nextFilter:MemoryView){setFilter(nextFilter);setFilterOpen(false);}
  const shownDatabasePath=databasePath??"Unavailable";

  return <main className="app-shell">
    <aside className="sidebar"><div className="wordmark">only—memories</div><div className="api-state"><i className={online?"online":"offline"}/>{online?"Local API online":"Local API offline"}</div><nav><button className={view==="memories"?"active":""} onClick={()=>setView("memories")}><Menu size={18}/>Memories</button><button className={view==="maintenance"?"active":""} onClick={()=>setView("maintenance")}><Sparkles size={18}/>Maintenance</button><button className={view==="settings"?"active":""} onClick={()=>setView("settings")}><Settings size={18}/>Settings</button></nav><div className="database-status"><Database size={16}/><strong>Database</strong><span>SQLite</span><code title={shownDatabasePath}>{shownDatabasePath}</code><small>{online?"Read / Write":"Unavailable"}</small></div></aside>
    {view==="maintenance"?<Maintenance proposals={proposals} memories={memories} busy={busy} previewedAt={previewedAt} onPreview={runPreview} onDecide={decide}/>:view==="settings"?<section className="settings-view"><h1>Settings</h1><div><MemoryStick/><span><strong>Local database</strong><small>SQLite · <code>{shownDatabasePath}</code></small></span><b>{online?"Connected":"Offline"}</b></div></section>:<>
      <section className="workspace"><header className="topbar"><h1>Memory explorer</h1><form className="search" onSubmit={submitSearch}><button type="submit" className="search-submit" aria-label="Submit search"><Search size={18}/></button><input ref={searchRef} value={query} onChange={event=>setQuery(event.target.value)} aria-label="Search memories" placeholder={scope==="general"?"Search current memory…":"Search all memory and history…"}/><kbd>⌘K</kbd></form><div className="scope"><button type="button" className={scope==="general"?"active":""} onClick={()=>setScope("general")}>Current</button><button type="button" className={scope==="remembering"?"active":""} onClick={()=>setScope("remembering")}>Remembering</button></div><div className="filter-control" ref={filterMenuRef}><button type="button" className="filter-button" aria-expanded={filterOpen} aria-controls="filter-menu" onClick={()=>setFilterOpen(value=>!value)}><Filter size={16}/>Filter</button>{filterOpen?<div id="filter-menu" className="filter-menu" role="menu">{filters.map(item=><button type="button" role="menuitemradio" aria-checked={filter===item} key={item} onClick={()=>selectFilter(item)}>{filter===item?<Check size={14}/>:<span/>}{item[0].toUpperCase()+item.slice(1)}</button>)}</div>:null}</div><button type="button" className="primary new-memory" onClick={startNewMemory}><Plus size={16}/>New memory</button></header>
      {error?<div className="error-banner">{error}<button onClick={()=>void load(filter)}>Retry</button></div>:null}<div className="explorer"><section className="list-panel"><div className="filter-tabs">{filters.map(item=><button key={item} className={filter===item?"active":""} onClick={()=>selectFilter(item)}>{item[0].toUpperCase()+item.slice(1)}</button>)}</div>{loading?<div className="loading">Loading local memory…</div>:<MemoryTable memories={visibleMemories} selectedId={selected?.id} onSelect={memory=>setSelectedId(memory.id)}/>}<div className="list-footer"><span>{visibleMemories.length} memories</span><span>Sorted by relevance</span></div></section><GraphView graph={graph} selected={selected} onSelect={memory=>setSelectedId(memory.id)}/></div><Composer editing={editing} open={composerOpen} resetToken={composerResetToken} textareaRef={composerRef} onOpenChange={setComposerOpen} onSave={save} onCancel={()=>setEditing(undefined)}/></section>
      <Inspector memory={selected} graph={graph} history={history} onEdit={startEditing} onForget={forget} onRestore={restore} onSelect={memory=>{setMemories(current=>current.some(item=>item.id===memory.id)?current:[...current,memory]);setSelectedId(memory.id)}}/>
    </>}
  </main>;
}
