import { FormEvent, useCallback, useDeferredValue, useEffect, useMemo, useState } from "react";
import { Database, Filter, MemoryStick, Menu, Plus, Search, Settings, Sparkles } from "lucide-react";
import { Composer, ComposerValue } from "./components/Composer";
import { GraphView } from "./components/GraphView";
import { Inspector } from "./components/Inspector";
import { Maintenance } from "./components/Maintenance";
import { MemoryTable } from "./components/MemoryTable";
import { GraphResponse, MaintenanceProposal, Memory, SearchScope, VersionHistory, createMemory, decideMaintenance, forgetMemory, getGraph, getVersions, health, listMaintenance, listMemories, previewMaintenance, restoreMemory, searchMemories, updateMemory } from "./api";

type View = "memories" | "maintenance" | "settings";
type FilterView = "all" | "axioms" | "forgotten" | "expired";

export function App() {
  const [view,setView]=useState<View>("memories"); const [filter,setFilter]=useState<FilterView>("all"); const [scope,setScope]=useState<SearchScope>("general"); const [query,setQuery]=useState(""); const deferredQuery=useDeferredValue(query);
  const [memories,setMemories]=useState<Memory[]>([]); const [selectedId,setSelectedId]=useState<string>(); const [graph,setGraph]=useState<GraphResponse|null>(null); const [history,setHistory]=useState<VersionHistory|null>(null); const [editing,setEditing]=useState<Memory>(); const [proposals,setProposals]=useState<MaintenanceProposal[]>([]);
  const [online,setOnline]=useState(false); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false); const [error,setError]=useState<string>();
  const selected=memories.find(memory=>memory.id===selectedId) ?? graph?.nodes.find(memory=>memory.id===selectedId) ?? graph?.origin;

  const load = useCallback(async (nextFilter: FilterView = filter) => { setLoading(true); setError(undefined); try { const [items] = await Promise.all([listMemories(nextFilter), health()]); setMemories(items); setSelectedId(current=>items.some(item=>item.id===current)?current:items[0]?.id); setOnline(true); } catch (reason) { setOnline(false); setError(reason instanceof Error?reason.message:"Could not reach local API"); } finally {setLoading(false);} },[filter]);
  useEffect(()=>{void load(); void listMaintenance().then(setProposals).catch(()=>undefined);},[load]);
  useEffect(()=>{if(!selectedId){setGraph(null);setHistory(null);return;} let active=true; Promise.all([getGraph(selectedId),getVersions(selectedId)]).then(([nextGraph,nextHistory])=>{if(active){setGraph(nextGraph);setHistory(nextHistory);}}).catch(()=>{if(active){setGraph(null);setHistory(null);}}); return()=>{active=false};},[selectedId]);

  const visibleMemories=useMemo(()=>{ if(filter==="forgotten") return memories.filter(memory=>memory.is_forgotten); if(filter==="expired") return memories.filter(memory=>memory.expires_at && new Date(memory.expires_at)<=new Date()); return [...memories].sort((a,b)=>(b.rank??0)-(a.rank??0)); },[memories,filter]);
  async function submitSearch(event:FormEvent){event.preventDefault();if(!deferredQuery.trim()){await load();return;}setLoading(true);try{const result=await searchMemories(deferredQuery.trim(),scope);setMemories(result.results);setSelectedId(result.results[0]?.id);}catch(reason){setError(reason instanceof Error?reason.message:"Search failed");}finally{setLoading(false);}}
  async function save(value:ComposerValue){try{const memory=editing?await updateMemory(editing.id,{content:value.content,cadence:value.cadence,base_importance:value.base_importance}):await createMemory({type:value.type,content:value.content,cadence:value.cadence,base_importance:value.base_importance,source:"manual-ui",source_links:value.sourceUri?[{label:value.sourceUri,kind:"manual",uri:value.sourceUri}]:[]});setEditing(undefined);await load("all");setSelectedId(memory.id);}catch(reason){setError(reason instanceof Error?reason.message:"Save failed");}}
  async function forget(){if(!selected)return;const reason=window.prompt("Why should this memory be forgotten?", "outdated or no longer relevant");if(reason===null)return;await forgetMemory(selected.id,reason);await load(filter);}
  async function restore(){if(!selected)return;await restoreMemory(selected.id);await load(filter);setSelectedId(selected.id);}
  async function runPreview(){setBusy(true);try{const run=await previewMaintenance();setProposals(run.proposals);}catch(reason){setError(reason instanceof Error?reason.message:"Maintenance preview failed");}finally{setBusy(false);}}
  async function decide(id:string,action:"apply"|"dismiss"){setBusy(true);try{const result=await decideMaintenance(id,action);setProposals(current=>current.map(item=>item.id===id?result.proposal:item));if(action==="apply")await load(filter);}finally{setBusy(false);}}

  return <main className="app-shell">
    <aside className="sidebar"><div className="wordmark">only—memories</div><div className="api-state"><i className={online?"online":"offline"}/>{online?"Local API online":"Local API offline"}</div><nav><button className={view==="memories"?"active":""} onClick={()=>setView("memories")}><Menu size={18}/>Memories</button><button className={view==="maintenance"?"active":""} onClick={()=>setView("maintenance")}><Sparkles size={18}/>Maintenance</button><button className={view==="settings"?"active":""} onClick={()=>setView("settings")}><Settings size={18}/>Settings</button></nav><div className="database-status"><Database size={16}/><strong>Database</strong><span>SQLite</span><code>~/.only-memories/memories.db</code><small>{online?"Read / Write":"Unavailable"}</small></div></aside>
    {view==="maintenance"?<Maintenance proposals={proposals} memories={memories} busy={busy} onPreview={runPreview} onDecide={decide}/>:view==="settings"?<section className="settings-view"><h1>Settings</h1><div><MemoryStick/><span><strong>Local database</strong><small>SQLite · ~/.only-memories/memories.db</small></span><b>{online?"Connected":"Offline"}</b></div></section>:<>
      <section className="workspace"><header className="topbar"><h1>Memory explorer</h1><form className="search" onSubmit={submitSearch}><Search size={18}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder={scope==="general"?"Search current memory…":"Search all memory and history…"}/><kbd>⌘K</kbd></form><div className="scope"><button className={scope==="general"?"active":""} onClick={()=>setScope("general")}>Current</button><button className={scope==="remembering"?"active":""} onClick={()=>setScope("remembering")}>Remembering</button></div><button className="filter-button"><Filter size={16}/>Filter</button><button className="primary new-memory" onClick={()=>{setEditing(undefined);document.querySelector(".composer")?.classList.add("open")}}><Plus size={16}/>New memory</button></header>
      {error?<div className="error-banner">{error}<button onClick={()=>void load()}>Retry</button></div>:null}<div className="explorer"><section className="list-panel"><div className="filter-tabs">{(["all","axioms","forgotten","expired"] as FilterView[]).map(item=><button key={item} className={filter===item?"active":""} onClick={()=>{setFilter(item);void load(item)}}>{item[0].toUpperCase()+item.slice(1)}</button>)}</div>{loading?<div className="loading">Loading local memory…</div>:<MemoryTable memories={visibleMemories} selectedId={selected?.id} onSelect={memory=>setSelectedId(memory.id)}/>}<div className="list-footer"><span>{visibleMemories.length} memories</span><span>Sorted by relevance</span></div></section><GraphView graph={graph} selected={selected} onSelect={memory=>setSelectedId(memory.id)}/></div><Composer editing={editing} onSave={save} onCancel={()=>setEditing(undefined)}/></section>
      <Inspector memory={selected} graph={graph} history={history} onEdit={()=>selected&&setEditing(selected)} onForget={forget} onRestore={restore} onSelect={memory=>{setMemories(current=>current.some(item=>item.id===memory.id)?current:[...current,memory]);setSelectedId(memory.id)}}/>
    </>}
  </main>;
}
